var freeingSpacesFromCSV = [
 {
   "Name*": "Zapatistas (EZLN)",
   "Type*": "Land / Food",
   "Website": "",
   "Description": "",
   "Latitude 1*": "17.342785394334100",
   "Longitute 1*": "-92.754202163673300",
   "Latitude 2": "17.452849644589000",
   "Longitute 2": "-92.666123642205000",
   "Latitude 3": "17.492856556614700",
   "Longitute 3": "-92.594821981968800",
   "Latitude 4": "17.571844332245900",
   "Longitute 4": "-92.519326106424500",
   "Latitude 5": "17.619820087221200",
   "Longitute 5": "-92.352606046913100",
   "Latitude 6": "17.698752385231600",
   "Longitute 6": "-92.348411831605100",
   "Latitude 7": "17.688762869701900",
   "Longitute 7": "-92.272915956060800",
   "Latitude 8": "17.773656017854300",
   "Longitute 8": "-92.195322972862600",
   "Latitude 9": "17.702748036077500",
   "Longitute 9": "-92.066350850541900",
   "Latitude 10": "17.846532088688100",
   "Longitute 10": "-91.926893191550400",
   "Latitude 11": "17.824572572885000",
   "Longitute 11": "-91.792678301693900",
   "Latitude 12": "17.735708758409700",
   "Longitute 12": "-91.829377685639100",
   "Latitude 13": "17.568321200726900",
   "Longitute 13": "-91.900837215441600",
   "Latitude 14":  "16.600463141649300",
   "Longitute 14": "-90.658286550764900",
   "Latitude 15": "16.089080428793800",
   "Longitute 15": "-90.958406010548700",
   "Latitude 16": "16.072909806027600",
   "Longitute 16": "-91.732545925505200",
   "Latitude 17": "15.735724514747200",
   "Longitute 17": "-91.928885762739100",
   "Latitude 18": "16.199375944163500",
   "Longitute 18": "-92.996709820142800",
   "Latitude 19": "16.728531874198800",
   "Longitute 19": "-92.558113715815800",
   "Latitude 20": "17.057949522272400",
   "Longitute 20": "-93.062735040149100"
 },
 {
   "Name*": "The Foundry",
   "Type*": "Projects",
   "Website": "https://bravosfoundry.com",
   "Description": "Non-profit and self-organized project space / residency",
   "Latitude 1*": "43.601181745652400",
   "Longitute 1*": "-7.641724521729830",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
  {
   "Name*": "Red Emmas",
   "Type*": "Projects",
   "Website": "http://redemmas.org",
   "Description": "Collective owned and operated coffeeshop & bookstore.",
   "Latitude 1*": "39.3042708485618",
   "Longitute 1*": "-76.6185152067866",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
  {
   "Name*": "2640 Space",
   "Type*": "Projects",
   "Website": "https://www.2640space.net/",
   "Description": "A noncommercial, collectively-managed space for radical politics & grassroots culture.",
   "Latitude 1*": "39.3204687498752",
   "Longitute 1*": "-76.615662197909",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "La Borda",
   "Type*": "Housing",
   "Website": "http://www.laborda.coop/en/",
   "Description": "Collectively owned cooperative housing project",
   "Latitude 1*": "41.369601042553900",
   "Longitute 1*": "2.134867347748790",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Autonome Wohnfabrik",
   "Type*": "Housing",
   "Website": "https://autonome-wohnfabrik.at/",
   "Description": "Collectively owned self-organized housing project",
   "Latitude 1*": "52.364415694068700",
   "Longitute 1*": "4.937410365508580",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Willy Fred",
   "Type*": "Housing",
   "Website": "https://www.willy-fred.org/",
   "Description": "Collectively owned self-organized housing project",
   "Latitude 1*": "48.306188794281900",
   "Longitute 1*": "14.290021074883300",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Regenbogenfabrik",
   "Type*": "Projects",
   "Website": "https://www.regenbogenfabrik.de/",
   "Description": "Former squat turned project space / hostel (solidary economy, direct democracy)",
   "Latitude 1*": "52.496342866092300",
   "Longitute 1*": "13.426970900007400",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "ZAD NDDL",
   "Type*": "Land / Food",
   "Website": "https://zad.nadir.org/",
   "Description": "A zone to defend",
   "Latitude 1*": "47.347792100331900",
   "Longitute 1*": "1.732647970502410",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Errekaleor ",
   "Type*": "Housing",
   "Website": "https://errekaleorbizirik.org/index.php/eu/",
   "Description": "The Basque Country's largest squat",
   "Latitude 1*": "42.835529414049600",
   "Longitute 1*": "2.650654755229440",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Milwaukee Autonomous Tenants Union",
   "Type*": "Housing",
   "Website": "http://www.matunion.org",
   "Description": "Dedicated dual power, direct action, rank & file tenants union",
   "Latitude 1*": "43.038902000000000",
   "Longitute 1*": "-87.906471000000000",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "I.W.W. Worker Owned Cooperative Shop",
   "Type*": "Projects",
   "Website": "http://mkegmb.org",
   "Description": "Buidling worker power, workplace democracy and worker-owned cooperative shops",
   "Latitude 1*": "43.038902000000000",
   "Longitute 1*": "-87.906471000000000",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Cooperation Milwaukee",
   "Type*": "Projects",
   "Website": "https://milwaukee.dsawi.org/get-involved/solidarity-mutual-aid/",
   "Description": "Seeding solidarity economy and mutual aid initiaves in occupied Sauk, Potawatomi, Ojibwe. Algonquian, and Menominee land",
   "Latitude 1*": "43.038902000000000",
   "Longitute 1*": "-87.906471000000000",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Milwaukee Cohousing & Cooperatives",
   "Type*": "Housing",
   "Website": "https://www.milwareacohousing.org",
   "Description": "Creating housing cooperatives in Milwaukee area, battling housing inequity",
   "Latitude 1*": "43.038902000000000",
   "Longitute 1*": "-87.906471000000000",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "AK Press",
   "Type*": "Projects",
   "Website": "https://www.akpress.org/",
   "Description": "Worker-managed, independent publisher and book distributor that specialises in radical left and anarchist literature. Operated out of Chico, California, the company is collectively owned.",
   "Latitude 1*": "39.806840000000000",
   "Longitute 1*": "-121.854190000000000",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Spaces below :Strasbourg, France",
   "Type*": "",
   "Website": "",
   "Description": "",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "La Maison Rose",
   "Type*": "Projects",
   "Website": "lamaisonrosegruber.org",
   "Description": "Free space with workshops",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Wagon Souk ",
   "Type*": "Projects",
   "Website": "https://www.facebook.com/LeWagonSouk/",
   "Description": "Free shop with plants and other stuff, Food kitchen for precarious people",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "L'Hôtel de la Rue",
   "Type*": "Housing",
   "Website": "https://larouetournestrasbourg.fr/",
   "Description": "Housing for the homeless, over 160 refugees living there",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "La Maison Mimir",
   "Type*": "Projects",
   "Website": "https://azqs.com/maison-mimir/",
   "Description": "Housing for the homeless and social / cultural events ",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Spaces below : Amsterdam",
   "Type*": "",
   "Website": "",
   "Description": "",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "OCCII",
   "Type*": "Projects",
   "Website": "https://occii.org/",
   "Description": "Cultural space",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Joe's Garage",
   "Type*": "Projects",
   "Website": "joesgarage.nl",
   "Description": "Autonomous space : solidarity and cultural events",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Vrankrijk",
   "Type*": "Projects",
   "Website": "vrankrijk.nl",
   "Description": "Historical cultural centre, originally squatted",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Editions Libertalia",
   "Type*": "Projects",
   "Website": "libertalia.fr",
   "Description": "Anarchist editor in Montreuil (Paris suburbs)",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Editions du commun",
   "Type*": "",
   "Website": "editionsducommun.fr",
   "Description": "Editor in Rennes with Opensource books online",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Soweto",
   "Type*": "Housing",
   "Website": "https://soweto.nl/en/about/projects",
   "Description": "Social housing cooperative",
   "Latitude 1*": "52.364402590358100",
   "Longitute 1*": "4.937453280438850",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "",
   "Type*": "",
   "Website": "",
   "Description": "",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Sostre Civic",
   "Type*": "Housing",
   "Website": "https://sostrecivic.coop/",
   "Description": "Tenant ownership / cooperative housing organization",
   "Latitude 1*": "41.392564418891100",
   "Longitute 1*": "2.174009899997200",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Ecodorp Boekel",
   "Type*": "Land / Food",
   "Website": "https://www.ecodorpboekel.nl/",
   "Description": "Eco-village in the Netherlands; member of VrijCoop",
   "Latitude 1*": "51.595760872992200",
   "Longitute 1*": "5.680674131342630",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Bajesdorp",
   "Type*": "Housing",
   "Website": "https://bajesdorp.nl/",
   "Description": "Cooperative housing / artist studio project in a former prison area; member of VrijCoop",
   "Latitude 1*": "52.336133681163300",
   "Longitute 1*": "4.927345203987230",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "De Groene Gemeenschap",
   "Type*": "Housing",
   "Website": "https://degroenegemeenschap.org/",
   "Description": "Cooperative housing project; member of VrijCoop, Soweto and Mietshäuser Syndikat",
   "Latitude 1*": "52.364544724983300",
   "Longitute 1*": "4.988028115881650",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Rijkshemelvaartdienst",
   "Type*": "Housing",
   "Website": "http://www.rijkshemelvaart.com/",
   "Description": "Former squat, now space for artists to work and live; member of VrijCoop",
   "Latitude 1*": "52.334742616873500",
   "Longitute 1*": "4.806939869054290",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Pension Almonde",
   "Type*": "Housing",
   "Website": "https://www.pension-almonde.nl",
   "Description": "Temporary home for urban nomads in an area planned to be demolished; member of Stad in de Maak",
   "Latitude 1*": "51.928927776168900",
   "Longitute 1*": "4.481239206550780",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Banierstraat 62",
   "Type*": "Housing",
   "Website": "https://www.stadindemaak.nl/banierstraat-62/",
   "Description": "Several artist studios in a former marijuana plantation; member of Stad in de Maak",
   "Latitude 1*": "51.930871285416300",
   "Longitute 1*": "4.472396993561460",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Bloklandstraat 190",
   "Type*": "Housing",
   "Website": "https://www.stadindemaak.nl/bloklandstraat-190/",
   "Description": "Housing / workspace; member of Stad in de Maak",
   "Latitude 1*": "51.937102208317800",
   "Longitute 1*": "4.478445076690650",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Pieter de Raadtstraat 35 & 37",
   "Type*": "Housing",
   "Website": "https://www.stadindemaak.nl/pieter-de-raadtstraat-35-37/",
   "Description": "Housing / workspace; member of Stad in de Maak",
   "Latitude 1*": "51.928947559868800",
   "Longitute 1*": "4.468970164010400",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Zwaanshals 288B",
   "Type*": "Housing",
   "Website": "https://www.stadindemaak.nl/zwaanshals-288-b/",
   "Description": "Housing / workspace; member of Stad in de Maak",
   "Latitude 1*": "51.933358617107000",
   "Longitute 1*": "4.486100363355460",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Nieuwland",
   "Type*": "Housing",
   "Website": "https://nieuwland.cc/",
   "Description": "Housing / project space",
   "Latitude 1*": "52.362402089807100",
   "Longitute 1*": "4.929990179281170",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "La Porcheritz",
   "Type*": "Housing",
   "Website": "http://clip.ouvaton.org/les-projets/",
   "Description": "Housing freed from the market; member of le Clip",
   "Latitude 1*": "48.865642425068200",
   "Longitute 1*": "2.406255346955150",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "La Déviation",
   "Type*": "Projects",
   "Website": "http://www.ladeviation.org/",
   "Description": "Space for artistic research; member of le Clip",
   "Latitude 1*": "43.368587779289700",
   "Longitute 1*": "5.306144439693700",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Køpi",
   "Type*": "Projects",
   "Website": "https://koepi137.net/welcome.html",
   "Description": "One of the last remaining original squats in Berlin",
   "Latitude 1*": "52.508070049213600",
   "Longitute 1*": "13.426335030683900",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Rigaer 94",
   "Type*": "Housing",
   "Website": "https://rigaer94.squat.net/",
   "Description": "One of the last remaining original squats in Berlin",
   "Latitude 1*": "52.517956809985400",
   "Longitute 1*": "13.458004040392200",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Manifesten",
   "Type*": "Projects",
   "Website": "https://www.facebook.com/manifesten/",
   "Description": "Project space; member of le Clip",
   "Latitude 1*": "43.297377082035900",
   "Longitute 1*": "5.385610531437690",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Woodbine",
   "Type*": "Projects",
   "Website": "https://www.woodbine.nyc/",
   "Description": "Woodbine is a volunteer-run experimental hub in Ridgewood, Queens for developing the practices, skills, and tools needed to build autonomy.",
   "Latitude 1*": "40.706597542060100",
   "Longitute 1*": "-73.908096187042800",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Performing Arts Forum",
   "Type*": "Projects",
   "Website": "https://www.pa-f.net",
   "Description": "PAF is a residency and a user-created, user-innovative informal institution for arts and sciences",
   "Latitude 1*": "49.5135734",
   "Longitute 1*": "3.835899181",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Bidston Observatory",
   "Type*": "Projects",
   "Website": "http://www.bidstonobservatory.org/",
   "Description": "Artistic research center and residency",
   "Latitude 1*": "53.40081088",
   "Longitute 1*": "-3.074224402",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Kerminy",
   "Type*": "Projects",
   "Website": "https://kerminy.org/",
   "Description": "Independent meeting place for artistic, research, theoretical and cultural production residencies; agricultural focus.",
   "Latitude 1*": "47.984951607481000",
   "Longitute 1*": "-3.833909963744380",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "KRA - Kravín Rural Arts",
   "Type*": "Projects",
   "Website": "http://kra.land/",
   "Description": "Artist residency with a focus on artistic-ecological research.",
   "Latitude 1*": "50.077732687188200",
   "Longitute 1*": "14.414986255634600",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Fritz Manor",
   "Type*": "Housing",
   "Website": "http://www.fritzmanor.com/",
   "Description": "Open residency for artists, writers, musicians, dancers, thinkers and the like.",
   "Latitude 1*": "53.711298728030900",
   "Longitute 1*": "12.827535725100200",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "MASSIA",
   "Type*": "Housing",
   "Website": "http://www.massia.ee",
   "Description": "MASSIA is a user-created informal residency space initiated and run by artists, theoreticians and practitioners.",
   "Latitude 1*": "57.998781225135900",
   "Longitute 1*": "24.588549515341900",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Konvent",
   "Type*": "Projects",
   "Website": "www.konventzero.com",
   "Description": "Konvent is a creative space that breathes life into disused industrial heritage.",
   "Latitude 1*": "42.075593181812100",
   "Longitute 1*": "1.870176223290080",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Calafou",
   "Type*": "Projects",
   "Website": "https://calafou.org",
   "Description": "Eco-industrial post-capitalist colony (self-organized and collectively owned)",
   "Latitude 1*": "41.511107696611000",
   "Longitute 1*": "1.703341926478310",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Rimaflow",
   "Type*": "Projects",
   "Website": "https://rimaflow.it/",
   "Description": "Self-organized workshops in an occupied car factory.",
   "Latitude 1*": "45.428931085354500",
   "Longitute 1*": "9.048748684658010",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "",
   "Type*": "",
   "Website": "",
   "Description": "",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Spaces below : Moscow",
   "Type*": "",
   "Website": "",
   "Description": "",
   "Latitude 1*": "",
   "Longitute 1*": "",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 },
 {
   "Name*": "Tolko Sami",
   "Type*": "Projects",
   "Website": "https://www.instagram.com/tolko_sami/",
   "Description": "Self-organized collectively managed cultural center",
   "Latitude 1*": "55.749658000000000",
   "Longitute 1*": "37.581451000000000",
   "Latitude 2": "",
   "Longitute 2": "",
   "Latitude 3": "",
   "Longitute 3": "",
   "Latitude 4": "",
   "Longitute 4": "",
   "Latitude 5": "",
   "Longitute 5": "",
   "Latitude 6": "",
   "Longitute 6": "",
   "Latitude 7": "",
   "Longitute 7": "",
   "Latitude 8": "",
   "Longitute 8": "",
   "Latitude 9": "",
   "Longitute 9": "",
   "Latitude 10": "",
   "Longitute 10": "",
   "Latitude 11": "",
   "Longitute 11": "",
   "Latitude 12": "",
   "Longitute 12": "",
   "Latitude 13": "",
   "Longitute 13": "",
   "Latitude 14": "",
   "Longitute 14": "",
   "Latitude 15": "",
   "Longitute 15": "",
   "Latitude 16": "",
   "Longitute 16": "",
   "Latitude 17": "",
   "Longitute 17": "",
   "Latitude 18": "",
   "Longitute 18": "",
   "Latitude 19": "",
   "Longitute 19": "",
   "Latitude 20": "",
   "Longitute 20": ""
 }
]